---
title: "panel model"
author: "Pengfei Luo"
date: "8/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# exploring panel data
```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta") 
coplot(y ~ year|country, type="l", data=Panel) # Lines
coplot(y ~ year|country, type="b", data=Panel) # Points and lines
```

```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta")
library(car)
scatterplot(y~year|country, boxplots=FALSE, smooth=TRUE, reg.line=FALSE, data=Panel)
```

## FIXED-EFFECTS MODEL
(Covariance Model, Within Estimator, Individual Dummy Variable Model, Least Squares Dummy Variable Model)

### Fixed effects: Heterogeneity across countries (or entities)
```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta") 
library(gplots)
plotmeans(y ~ country, main="Heterogeineity across countries", data=Panel)
# plotmeans draw a 95% confidence interval around the means
detach("package:gplots")
# Remove package ‘gplots’ from the workspace
```

### Fixed effects: Heterogeneity across years
```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta")
library(gplots)
plotmeans(y ~ year, main="Heterogeineity across years", data=Panel)
# plotmeans draw a 95% confidence interval around the means
detach("package:gplots")
# Remove package ‘gplots’ from the workspace
```

### OLS regression
```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta")
ols <-lm(y ~ x1, data=Panel)
summary(ols)


# plot 
yhat <- ols$fitted
plot(Panel$x1, Panel$y, pch=19, xlab="x1", ylab="y")
abline(lm(Panel$y~Panel$x1),lwd=3, col="red")
```

### Fixed effects using Least squares dummy variable model
```{r}
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta")
fixed.dum <-lm(y ~ x1 + factor(country) - 1, data=Panel)
summary(fixed.dum)
```
### Least squares dummy variable model
```{r}
yhat <- fixed.dum$fitted
library(car)
scatterplot(yhat~Panel$x1|Panel$country, boxplots=FALSE, xlab="x1", ylab="yhat",smooth=FALSE) 
abline(lm(Panel$y~Panel$x1),lwd=3, col="red")
```

